blogs/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from blogs import views as contact_views

app_name = 'blogs'
urlpatterns = [
    path('', views.index_page, name='index'),
    path(_('about/'), views.about_page, name='about'),

    path(_('news/'), views.NewsListView.as_view(), name='news_list'),
    path(_('news/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.NewsDetailView.as_view(), name='news_detail'),

    path(_('tender/'), views.TenderListView.as_view(), name='tender_list'),
    path(_('tender/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.TenderDetailView.as_view(),
         name='tender_detail'),

    path(_('product/'), views.ProductListView.as_view(), name='product_list'),

    path(_('membership/'), views.MembershipListView.as_view(), name='membership_list'),
    path(_('membership/<slug:slug>'), views.MembershipDetailView.as_view(), name='membership_detail'),

    path(_('exhibitions/'), views.ExhibitionListView.as_view(), name='exhibition'),
    path(_('exhibitions/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.ExhibitionDetailView.as_view(),
         name='exhibition_detail'),

    path(_('gallery/'), views.GalleryListView.as_view(), name='gallery'),

    # path(_('gallery/'), views.Gallery, name='gallery'),

    path(_('media/'), views.MediaListView.as_view(), name='media'),

    path(_('vacancy/'), views.VacancyListView.as_view(), name='vacancy'),

    path(_('faq/'), views.FAQListView.as_view(), name='faq'),

    path(_('contact/'), contact_views.contact_view, name='contact_form'),

    path(_('virtual_reception/'), views.virtual_reception_view, name='virtual_reception_form'),

    path(_('entrepreneurs/'), views.EntrepreneursListView.as_view(), name='entrepreneurs'),

    path(_('membership_procedure/'), views.MembershipProcedureListView.as_view(), name='membership_procedure'),

    path(_('benefits/)'), views.BenefitListView.as_view(), name='benefits'),

    path(_('content/<slug:slug>'), views.StaticContentView.as_view(), name='static_page'),

    # path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal'),

    path(_('legal/'), views.LegalDocumentListView.as_view(), name='legal'),

    path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal_detail'),

    path(_('statistic/'), views.StatisticListView.as_view(), name='statistic_list'),

    path(_('statistic/<slug:slug>'), views.StatisticDetailView.as_view(), name='statistic_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from users import views as user_view
import users


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('user/', include('users.urls')),
)

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Uzcharmsanoat admin panel"
admin.site.site_title = "Uzcharmsanoat Admin Portal"
admin.site.index_title = "Welcome to Uzcharmsanoat Portal"

templates/blogs/pages/virtual_reception/virtual_reception_form.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}

    <section class="all__news" style="background: url('{% static 'assets/images/bannerimg.png' %}')">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-md-12">
                    <div class="heading_news-all">
                        <h1>{% trans 'VIRTUAL RECEPTION' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-md-12 page-title-head_2">
                <h1>{% trans 'VIRTUAL RECEPTION' %}</h1>
            </div>

            <div class="card overflow-hidden online__reception border-0">
                <form action="{% url 'blogs:virtual_reception_form' %}" method="POST">
                    {% csrf_token %}
                    <div class="card-body row">

                        <div class="col-md-6">
                            <label for="full_nam">{% trans 'Full Name' %}</label>
                            <input id="full_nam" type="text" name="full_nam" class="form-control input__form_con"
                                   required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="email">{% trans 'E-mail' %}</label>
                            <input id="email" type="email" name="email" class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="phone_number">{% trans 'Phone number' %}</label>
                            <input id="phone_number" type="text" name="phone_number"
                                   class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="region">{% trans 'Select a region' %}</label>
                            <input id="region" type="text" name="region" class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="address">{% trans 'Address' %}</label>
                            <input id="address" type="text" name="address" class="form-control input__form_con"
                                   required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="date_of_birth">{% trans 'Date of birth' %}</label>
                            <input id="date_of_birth" type="date" name="date_of_birth"
                                   class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="gender">{% trans 'Gender' %}</label>
                            <input id="gender" type="text" name="gender" class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <label for="marital_status">{% trans 'Marital status' %}</label>
                            <input id="marital_status" type="text" name="marital_status"
                                   class="form-control input__form_con" required>
                        </div>

                        <div class="col-lg-12 col-md-12 mb-2">
                            <button class="file-upload1 form-control mt-0">
                                <input id="file_uploa" type="file" name="file_uploa" class="file-input" size="100">
                                <i class="fa fa-cloud-upload"
                                   aria-hidden="true"></i>&nbsp;&nbsp;{% trans 'Upload file' %}
                            </button>
                        </div>

                        <div class="col-lg-12">
                            <label for="message">{% trans 'Message' %}</label>
                            <textarea name="message" id="message" cols="30" rows="10"
                                      class="w-100 form-control input__form_con" required>
                            </textarea>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-check">
                                <input class="form-check-input input__form_con" type="checkbox" value=""
                                       id="defaultCheck1" required>
                                <label class="form-check-label" for="defaultCheck1">
                                    {% trans 'Allow my question to be published' %}
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <button class="outline-none mt-3 btn__send btn btn-primary">{% trans 'Send' %}</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}