blogs/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from blogs import views as contact_views

app_name = 'blogs'
urlpatterns = [
    path('', views.index_page, name='index'),
    path(_('about/'), views.about_page, name='about'),

    path(_('news/'), views.NewsListView.as_view(), name='news_list'),
    path(_('news/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.NewsDetailView.as_view(), name='news_detail'),

    path(_('tender/'), views.TenderListView.as_view(), name='tender_list'),
    path(_('tender/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.TenderDetailView.as_view(),
         name='tender_detail'),

    path(_('product/'), views.ProductListView.as_view(), name='product_list'),

    path(_('membership/'), views.MembershipListView.as_view(), name='membership_list'),
    path(_('membership/<slug:slug>'), views.MembershipDetailView.as_view(), name='membership_detail'),

    path(_('exhibitions/'), views.ExhibitionListView.as_view(), name='exhibition'),
    path(_('exhibitions/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.ExhibitionDetailView.as_view(),
         name='exhibition_detail'),

    path(_('gallery/'), views.GalleryListView.as_view(), name='gallery'),

    # path(_('gallery/'), views.Gallery, name='gallery'),

    path(_('media/'), views.MediaListView.as_view(), name='media'),

    path(_('vacancy/'), views.VacancyListView.as_view(), name='vacancy'),

    path(_('faq/'), views.FAQListView.as_view(), name='faq'),

    path(_('contact/'), contact_views.contact_view, name='contact_form'),

    path(_('virtual_reception/'), views.virtual_reception_view, name='virtual_reception_form'),

    path(_('entrepreneurs/'), views.EntrepreneursListView.as_view(), name='entrepreneurs'),

    path(_('membership_procedure/'), views.MembershipProcedureListView.as_view(), name='membership_procedure'),

    path(_('benefits/)'), views.BenefitListView.as_view(), name='benefits'),

    path(_('content/<slug:slug>'), views.StaticContentView.as_view(), name='static_page'),

    # path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal'),

    path(_('legal/'), views.LegalDocumentListView.as_view(), name='legal'),

    path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal_detail'),

    path(_('statistic/'), views.StatisticListView.as_view(), name='statistic_list'),

    path(_('statistic/<slug:slug>'), views.StatisticDetailView.as_view(), name='statistic_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from users import views as user_view
import users


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('user/', include('users.urls')),
)

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Uzcharmsanoat admin panel"
admin.site.site_title = "Uzcharmsanoat Admin Portal"
admin.site.index_title = "Welcome to Uzcharmsanoat Portal"

templates/blogs/pages/tender/detail.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-5 mb-5">

                <div class="detail-date">
                    <h4>{{ tender.created|date:"Y/m/d" }}</h4>
                </div>

                <div class="detail-title">
                    <h3>{{ tender.title }}</h3>
                </div>

                <div class="detail-description">{{ tender.main_text|safe }}</div>

            </div>

            <div class="col-md-12 mb-5 borderrable">
                <div class="news-detail__social">
                    <div class="row justify-content-around align-items-center">


                        <div>
                            <i class="fas fa-share mr-2"></i>{% trans 'share' %}
                        </div>


                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ post.title }}"
                           class="btn-main-over text-decoration-none text-center">
                            <i class="fab fa-facebook-f mr-2"></i>Facebook
                        </a>


                        <a href="https://twitter.com/share?url={{ request.build_absolute_uri }}&amp;text={{ post.title }}"
                           class="btn-main-over text-decoration-none text-center">
                            <i class="fab fa-twitter mr-2"></i>Twitter
                        </a>

                        <a href="https://telegram.me/share/url?url={{ request.build_absolute_uri }}&amp;text={{ post.title }}"
                           class="btn-main-over text-decoration-none text-center">
                            <i class="fab fa-telegram mr-2"></i>Telegram
                        </a>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blogs/pages/tender/list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}

    <section class="all__news" style="background: url('{% static 'assets/images/bannerimg.png' %}')">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-md-12">
                    <div class="heading_news-all">
                        <h1>{% trans 'Announcements and Tenders' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container">
    <div class="row mt-5">

        <div class="col-lg-12 mb-5">
           <div class="card columns__dates border-0">
               <div class="card-body">
                    <div class="row">
                <div class="col-lg-3 col-md-4 col-12">
                    <label>{% trans 'From' %}</label>
                    <input type="date" class="form-control advert__date">
                </div>
                <div class="col-lg-3 col-md-4 col-12">
                    <label>{% trans 'To' %}</label>
                    <input type="date" class="form-control advert__date">
                </div>
                <div class="col-lg-3 col-md-4 col-12">
                    <label>{% trans 'Show' %}</label>
                    <button class="btn btn__advert text-white form-control">{% trans 'Show' %}</button>
                </div>
            </div>
               </div>
           </div>
        </div>

        {% for item in tenders %}
            <div class="col-lg-4 col-md-6 col-12 mb-4">
                <a href="{% url 'blogs:tender_detail' item.created.year item.created.month item.created.day item.slug %}" class="card border-0 advertising__card text-decoration-none">
                    <div class="card-body">
                        <div class="advertising__title">
                            {{ item.title }}
                        </div>
                        {{ item.created|date }}
                        <div class="advertising__arrow">
                            <i class="far fa-arrow-right"></i>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}