blogs/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from blogs import views as contact_views

app_name = 'blogs'
urlpatterns = [
    path('', views.index_page, name='index'),
    path(_('about/'), views.about_page, name='about'),

    path(_('news/'), views.NewsListView.as_view(), name='news_list'),
    path(_('news/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.NewsDetailView.as_view(), name='news_detail'),

    path(_('tender/'), views.TenderListView.as_view(), name='tender_list'),
    path(_('tender/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.TenderDetailView.as_view(),
         name='tender_detail'),

    path(_('product/'), views.ProductListView.as_view(), name='product_list'),

    path(_('membership/'), views.MembershipListView.as_view(), name='membership_list'),
    path(_('membership/<slug:slug>'), views.MembershipDetailView.as_view(), name='membership_detail'),

    path(_('exhibitions/'), views.ExhibitionListView.as_view(), name='exhibition'),
    path(_('exhibitions/<int:year>/<int:month>/<int:day>/<slug:slug>'), views.ExhibitionDetailView.as_view(),
         name='exhibition_detail'),

    path(_('gallery/'), views.GalleryListView.as_view(), name='gallery'),

    # path(_('gallery/'), views.Gallery, name='gallery'),

    path(_('media/'), views.MediaListView.as_view(), name='media'),

    path(_('vacancy/'), views.VacancyListView.as_view(), name='vacancy'),

    path(_('faq/'), views.FAQListView.as_view(), name='faq'),

    path(_('contact/'), contact_views.contact_view, name='contact_form'),

    path(_('virtual_reception/'), views.virtual_reception_view, name='virtual_reception_form'),

    path(_('entrepreneurs/'), views.EntrepreneursListView.as_view(), name='entrepreneurs'),

    path(_('membership_procedure/'), views.MembershipProcedureListView.as_view(), name='membership_procedure'),

    path(_('benefits/)'), views.BenefitListView.as_view(), name='benefits'),

    path(_('content/<slug:slug>'), views.StaticContentView.as_view(), name='static_page'),

    # path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal'),

    path(_('legal/'), views.LegalDocumentListView.as_view(), name='legal'),

    path(_('legal/<slug:slug>'), views.LegalDocumentView.as_view(), name='legal_detail'),

    path(_('statistic/'), views.StatisticListView.as_view(), name='statistic_list'),

    path(_('statistic/<slug:slug>'), views.StatisticDetailView.as_view(), name='statistic_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from users import views as user_view
import users


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('user/', include('users.urls')),
)

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Uzcharmsanoat admin panel"
admin.site.site_title = "Uzcharmsanoat Admin Portal"
admin.site.index_title = "Welcome to Uzcharmsanoat Portal"

templates/blogs/pages/contact_page/contact_form.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <section class="all__news" style="background: url('{% static 'assets/images/bannerimg.png' %}')">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-md-12">
                    <div class="heading_news-all">
                        <h1>{% trans 'Contact' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="content">
        <div class="container">
            <div class="row mb-5">
                <div class="col-12">
                    <div>
                        {% for message in messages %}
                            <div class="alert alert-{{ message.level_tag }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row  no-gutters contact-wrap shadow-lg">
                <div class="col-md-8">
                    <div class="form h-100">
                        <h3>{% trans 'Contact' %}</h3>

                        <form action="{% url 'blogs:contact_form' %}" method="post">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-6 form-group mb-2">
                                    <label for="full_name" class="col-form-label">{% trans 'Your name' %}</label>
                                    <input id="full_name" type="text" name="full_name" class="form-control" required>
                                </div>
                                <div class="col-md-6 form-group mb-2">
                                    <label for="email" class="col-form-label">{% trans 'E-mail' %}</label>
                                    <input id="email" type="text" name="email" class="form-control" required>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 form-group mb-2">
                                    <label for="phone_number" class="col-form-label">{% trans 'Phone number' %}</label>
                                    <input id="phone_number" type="text" name="phone_number" class="form-control" required>
                                </div>
                                <div class="col-md-6 form-group mb-2">
                                    <label for="subject" class="col-form-label">{% trans 'Subject' %}</label>
                                    <input id="subject" type="text" name="subject" class="form-control" required>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 form-group mb-2">
                                    <label for="message" class="col-form-label">{% trans 'Message' %}</label>
                                    <textarea id="message" class="form-control" name="message" cols="30" rows="4" required></textarea>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <input type="submit" class="btn__send_contact radius-5 text-decoration-none" value="{% trans 'Send' %}">
                                </div>
                            </div>

                            <div>
                                <iframe src="https://yandex.uz/map-widget/v1/-/CCU4q4bOkA" width="100%" height="300"
                                        frameborder="1" allowfullscreen="true" class="border-0 shadow">
                                </iframe>
                            </div>
                        </form>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="contact-info h-100">
                        <h3>{% trans 'Feedback' %}</h3>
                        <p class="mb-4 text-white">
                            <i class="fas fa-map-marked-alt mr-3 mb-2"></i>
                            100192, Узбекистан, Ташкент, Мирзо-Улугбекский район, проспект Мустакиллик,
                            д.109{{ item.address }}</p>
                        <ul class="list-unstyled">
                            <li class="d-flex">
                                <span class="text mb-3 text-white">Ассоциация «Узчармсаноат»{{ item.address }}</span>
                            </li>
                            <li class="d-flex">
                                <a href="tel:+998 (71) 267-53-64" class="text text-white text-decoration-none">
                                    <i class="fas fa-phone-square-alt mr-3"></i>
                                    +998 (71) 267-53-64
                                </a>
                            </li>
                            <li class="d-flex">
                                <a href="mailto:info@uzcharm.com" class="text-white mb-2 text-decoration-none">
                                    <i class="fal fa-envelope-open-text mr-3"></i>
                                    info@uzcharm.com
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}